version: '3.9'
services:
  app:
    build:
      context: .
      args:
        - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      - GOOGLE_STORAGE_BUCKET
      - APILAYER_KEY
      - REDIS_URL
      - TOKEN_KEY
      - NODE_ENV=${APP_PORT:-production}
      - APP_PORT=${APP_PORT:-3000}
      - REDIS_URL=redis://redis:6379
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DBNAME=bnmofin
    ports:
      - ${APP_PORT:-3000}:${APP_PORT:-3000}
  db:
    image: postgres:14
    restart: always
    ports:
      - 127.0.0.1:${DB_LOCALPORT:-5433}:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bnmofin
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 127.0.0.1:${REDIS_LOCALPORT:-6380}:6379
    expose:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  db:
    driver: local