version: '3.9'
services:
  app:
    build:
      context: .
      args:
        - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/bnmofin}
      - DATABASE_SSL=${DATABASE_SSL:-no}
      - GOOGLE_STORAGE_BUCKET
      - GOOGLE_STORAGE_PREFIX
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_EX
      - APILAYER_KEY
      - JWT_KEY
      - SEED_DATA
      - SEED_INFO
    ports:
      - ${PORT:-3000}:${PORT:-3000}
  db:
    image: postgres:14
    restart: always
    ports:
      - ${DATABASE_HOSTPORT:-5433}:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bnmofin
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - ${REDIS_HOSTPORT:-6380}:6379
    expose:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  db:
    driver: local