version: '3.9'
services:
  app:
    build:
      context: .
      args:
        - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      - GOOGLE_STORAGE_BUCKET
      - APILAYER_KEY
      - REDIS_URL
      - TOKEN_KEY
      - NODE_ENV=${PORT:-production}
      - PORT=${PORT:-3000}
      - SEED_DATA=${SEED_DATA:-no}
      - SEED_INFO=${SEED_INFO:-no}
      - REDIS_URL=${REDIS_URL:-"redis://redis:6379"}
      - DATABASE_URL=${DATABASE_URL:-"postgres://postgres:postgres@db/bnmofin"}
      - DATABASE_SSL=${DATABASE_SSL:-no}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
  db:
    image: postgres:14
    restart: always
    ports:
      - 127.0.0.1:${DATABASE_HOSTPORT:-5433}:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bnmofin
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 127.0.0.1:${REDIS_HOSTPORT:-6380}:6379
    expose:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  db:
    driver: local